name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  integration:
    name: Running integration steps
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    
    steps:
      - uses: actions/checkout@v2
        
      - name: Installing dependencies
        run: npm install
      
      - name: Running linter
        run: npm run lint
        
      - name: Running tests
        run: npm test
